### ISSUE TITLE
Write-RsFolderContent - check if folder exists

### ISSUE THREAD

**Issue by martkopecky** [Microsoft/ReportingServicesTools#124]
I would like to report an improvement request.

Currently, the Write-RsFolderContent fails if a folder (or subfolder with -Recursive) already exists in the target. It would be better to check whether the target folder already exists and if it does, do not try to create it once again.

The expected behaviour is - if the folder on the target exists, do not touch it. At least with the override flag.

**Comment by parthsha** [comment]
This sounds like a great idea to me. Please feel free to make this change and send a PR to us! The community will definitely appreciate it!

**Comment by mika-n** [comment]
This enhancement was exactly what I needed while ago because the problem made it next to impossible to re-import existing folder tree structure without first removing existing folder tree . I modified modules/ReportingServicesTools/ReportingServicesTools/Functions/CatalogItems/Write-RsFolderContent.ps1 file as follows (only couple lines of code to wrap folder creation into if-then-else block):

OLD CODE IN THE FILE:
                Write-Verbose "Creating folder $parentFolder/$($item.Name)"
                try
                {
                    $Proxy.CreateFolder($item.Name, $parentFolder, $null) | Out-Null
                }
                catch
                {
                    throw (New-Object System.Exception("Failed to create folder '$($item.Name)' in '$parentFolder': $($_.Exception.Message)", $_.Exception))
                }

NEW MODIFIED CODE:
                try
                {
			if ( $Proxy.GetItemType("$parentFolder/$($item.Name)") -ne "Folder" )
			{
				Write-Verbose "Creating folder $parentFolder/$($item.Name)"
				$Proxy.CreateFolder($item.Name, $parentFolder, $null) | Out-Null
			}
			else
			{
				Write-Verbose "Folder already exists $parentFolder/$($item.Name)"
			}
                }
                catch
                {
                    throw (New-Object System.Exception("Failed to create folder '$($item.Name)' in '$parentFolder': $($_.Exception.Message)", $_.Exception))
                }


After you modify the file then remember to run "Import-Module ReportingServicesTools -force" command in existing PowerShell shell to force it to read modified script file (otherwise it may not see the changes because PS has cached the old script in memorhy).

**Comment by wsuhoey** [comment]
I had lots of trouble getting @mika-n's modified code to work. I did a copy/paste overwriting the precise `OLD CODE IN FILE` code with the modified code. My ISE was giving me errors on the $($.Exception.Message)", $.Exception changes. I changed back to the $_ parts and it seemed to no longer complain about missing brackets.

Can we get a valid PR for this so that it's integrated without an amateur such as myself changing code he doesn't fully understand?
