### ISSUE TITLE
Cannot add multiple Roles for NetworkService user using Grant-RsCatalogItemRole 

### ISSUE THREAD

**Issue by samuel-mason** [Microsoft/ReportingServicesTools#139]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When creating multiple or additional role assignments on the NetworkService user account we get the following error

![image](https://user-images.githubusercontent.com/29472536/35713808-60d41c08-0797-11e8-9a5e-233c13501d45.png)

Similar to #102 but instead of a specific user this happens on NetworkService.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create new folder - works
New-RsFolder -ReportServerUri $reportServerUri -RsFolder "/" -FolderName "Folder"

Grant permissions - works
Grant-RsCatalogItemRole -ReportServerUri $reportServerUri -Path "/Folder" -RoleName 'Browser' -Identity "NetworkService"

Add another role - fails
Grant-RsCatalogItemRole -ReportServerUri $reportServerUri -Path "/Folder" -RoleName 'Content Manager' -Identity "NetworkService"

**What is the expected behavior?**
The new role assignment is added to the current role assignment.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PowerShell v5.0
Windows 10

I have not used previous versions of these scripts so I do not know if it used to work or not.

**Comment by ClaudioESSilva** [comment]
The method (`SetPolicies`) accepts the partial name `NETWORK SERVICE` but when it saves it is translated to `NT AUTHORITY\NETWORK SERVICE` automatically.

The problem is that during the verification to validate if the user already exists or not it is using an `-eq` (equals) operator as the `NT AUTHORITY\NETWORK SERVICE` is not equal to `NETWORK SERVICE` he tries to add a new user called `NT AUTHORITY\NETWORK SERVICE` but in fact it already exists and hence the error.

The best practice (or workaround) here is to use the "full name"  `NT AUTHORITY\NETWORK SERVICE`´.

> I think we should add a warning saying something like "Please verify if you have typed the full name. You can get the current permissions by running the `Get-RsCatalogItemRole` command"

If @Prabhat-MSFT and/or @jtarquino agree I can add it as an improvement.

**Comment by jtarquino** [comment]
Hi @ClaudioESSilva it sounds good
