### ISSUE TITLE
The installation of ReportingServicesTools generates some error message

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#161]
Hi, 
I run the command below  as Administrator Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/ReportingServicesTools/master/Install.ps1), but I obtain only the error message you can find attached file.
![error message](https://user-images.githubusercontent.com/38687599/39180547-b548677c-47a6-11e8-8a9e-5fcd4688318e.PNG)

I don't understand what's happened.

Can you help me.

Best regards.

Wei

**Comment by ClaudioESSilva** [comment]
Hi @ssicefox,

The problem seems to be on the Invoke-WebRequest.

Can you run the following command and then, the Invoke-Expression

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12


Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.
com/Microsoft/ReportingServicesTools/master/Install.ps1)


Cumprimentos,
Cláudio Silva
_____________________
PowerShell MVP
<https://mvp.microsoft.com/en-us/PublicProfile/5002259?fullName=Cl%C3%A1udio%20%20Silva>
*e-mail:* claudiosil100@gmail.com
*linkedin:* https://pt.linkedin.com/in/claudioessilva
*twitter:* http://www.twitter.com/claudioessilva
*blog*: https://claudioessilva.eu/

**Comment by ssicefox** [comment]
Hi, Cláudio,

Thank you for your reply.

I run the command you provided me, then I run the command Invoke-Expression, but PowerShell generates the other error message you can find attached file.

Best regards.
Wei
![capture](https://user-images.githubusercontent.com/38687599/39299198-b1ed4074-4937-11e8-8f5d-71b117248d37.PNG)

**Comment by jtarquino** [comment]
You need to change your execution policy to allow them to run, check the set-executionpolicy command

Just ouf of curiosity, why not use the gallery version Install-Module -Name ReportingServicesTools 
https://www.powershellgallery.com/packages/ReportingServicesTools
