### ISSUE TITLE
Write-RsRestCatalogItem fails to upload non-ascii-named files with HTTP 422 error

### ISSUE THREAD

**Issue by AndrewSorokin** [Microsoft/ReportingServicesTools#202]
When I try to upload non-ascii-named PowerBI report files it fails with http 422.

Bug at ConverTo-Json

Workarond to download module manually and fix Write-RsRestFolderContent.ps1 
Then reload module.

`
...
$payloadJson = ConvertTo-Json $payload
### FIX: add line below to fix non ascii json payload 
$payloadJson = ([System.Text.Encoding]::UTF8.GetBytes($payloadJson))
### /FIX
...
`
Regards, Andrew Sorokin

PowerShell 

PSVersion                      5.1.16299.785
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.785
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ClaudioESSilva** [comment]
I have a code for this as for the `New-RsFolder` command.
I will submit PR in few days.

**Comment by GitHubJedi** [comment]
@ClaudioESSilva I work w/ fairly large .pbix files (500MB+) and noticed this change created memory problems with PowerShell for large reports because the report byte array gets loaded into mem like 2-3 different times. I was able to get the script to work by reverting the code back to only using $payloadJson with no conversion for non-ASCII characters. 

Maybe there is a more efficient method? May look into a solution myself on this/contribute but would be a learning experience. Seen some stuff about FileStreams helping w/ large byte arrays, using Encoder class instead of Encoding but not sure if this can work w/ the Invoke-WebRequest
