### ISSUE TITLE
Import-RsSubscriptionXML - just not importing

### ISSUE THREAD

**Issue by gorkam23** [microsoft/ReportingServicesTools#252]
I believe this is a bug, not user error.  

Import-RsSubscriptionXML has a -path parameter as a default, so in theory it should just work as per the first example.

Import-RsSubscriptionXML .\yourfilename.xml

It's generating the output, but it's not writing to the ReportServer database at all.  I looked at the code and I could not find anything obvious.  Despite the instructions (and I happy to update them once this is resolved), I can't see how Set-RsSubscription would make any difference.  

I believe the intent of this was to run on its own and not needing to pipe anything.  It's going to take a .XML file from Export-RsSubscriptionXML and reimport it.  

Please see the attached image.  

![Import-RsSubscriptionXML_error](https://user-images.githubusercontent.com/32223642/65045763-40212c80-d914-11e9-9c25-899c75a1e123.png)

**Comment by jtarquino** [comment]
I have done a little bit of digging, Import-RsSubscription is only meant to load the xml into an object that can be used later (basically gets the same object that if you were calling Get-RsSubscription)

My guess is you are trying to copy subscriptions , the two main use cases are

1. In the same server copy the subscription to a different report, you achieve that with 
Get-RsSubscription -RsItem "/imageOnly" | Copy-RsSubscription -RsItem "/imageOnlyCopy"
2. Export the subscription as a file and them create the subscription in a different report based on the xml file
Get-RsSubscription -RsItem "/imageOnly" | Export-RsSubscriptionXml ImageSubscriptionDefinition.xml
Import-RsSubscriptionXML ImageSubscriptionDefinition.xml | Copy-RsSubscription -RsItem "/imageOnlyCopy"


Probably the confusion started when the documentation wasn't updated properly when the cmdlets were updated for example what Import-RsSubscriptionXml docs says is 
"This script imports a subscription and rebuilds the SRSS specific properties so that the resultant object will be accepted by Set-RsSubscription." instead of Set-RsSubscription it should mention Copy-RsSubscription
