### ISSUE TITLE
Get-RsCatalogItemRole

### ISSUE THREAD

**Issue by js0505** [Microsoft/ReportingServicesTools#62]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to run Get-RsCatalogItemRole -ReportServerUri 'http://localhost/ReportServer' -Path "/" but when I execute I keep getting New-RsCatalogItemRoleObject : Unable to find type.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Get-RsCatalogItemRole -ReportServerUri 'http://localhost/ReportServer' -Path "/" 

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I do not know about previous versions, running OS windows server 2012 R2 and PS 4 module version 0.0.2.4
![reportingservicestools_error](https://user-images.githubusercontent.com/15731154/29133814-49c32cd4-7cfa-11e7-8576-1c9123e6ad40.png)

**Comment by djeepy1** [comment]
Get the same bug against Power BI Report Server
-Powershell version : 4
-PBIRS version : 14.0.600.301 (June GA) 
-Windows version : 2012 R2 x64 Standard French

Any ETA for a fix ?

Thank you

**Comment by ClaudioESSilva** [comment]
I found the problem here.

If you see the line https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Utilities/New-RsCatalogItemRoleObject.ps1#L41 you will find that `WebServiceProxy1tserver_ReportService2010_asmx` should be different for your case and different for mine unless our instance is named 'tserver'.

If you have an instance called `Server1` this part of the code should be:
WebServiceProxy1**Server1**_ReportService2010_asmx.

We can workaround this by saying this parameter is an object[] instead.
![image](https://user-images.githubusercontent.com/19521315/29577813-c0795a3c-8764-11e7-99d8-d79ea9b12001.png)

IMO, this change is not a problem because the function only iterate the collection of policies. No work based on his type (Policy) is done. Is just an `System.Array`
![image](https://user-images.githubusercontent.com/19521315/29577898-1b5d49cc-8765-11e7-82ac-d6e90e36e6f5.png)


@jtarquino if you agree with this fix/workaround let me know and I can submit a PR.

**Comment by jeremymcgee73** [comment]
That should work. I was looking at this today as well. I did not realize that the type changed when I wrote this. I was just trying to ensure that the correct type was passed to the function. @jtarquino  @ClaudioESSilva

**Comment by jtarquino** [comment]
@ClaudioESSilva  sounds good send the PR please

**Comment by ClaudioESSilva** [comment]
PR submitted: https://github.com/Microsoft/ReportingServicesTools/pull/64

**Comment by djeepy1** [comment]
Thank you @ClaudioESSilva !
